=pod

=head1 NAME

Package::Autoloader - merged back into Package::Tranporter

=head1 DESCRIPTION

Package::Autoloader was a fork from Package::Tranporter and has finally been merged back. Version 0.15 of Package::Autoloader can be considered to be the same as version 0.80 of Package::Tranporter. It has greatly speed up the development of the interface with a convincing result in terms of convenience and consistency. But it is no longer needed as a separate package, therefore removing from CPAN.

=head2 COPYRIGHT

Copyright (C) 2010 Winfried Trumper

=cut
